new start
Starrkkiller/ReactApp pull request #3
Opened 2022-10-23 13:14 UTC by Starrkkiller

Starting from start

2022-11-06 23:13 UTC, Muslik commented
У вас не все файлы отображаются в коммите.

2022-11-06 23:16 UTC, Muslik commented
<img width="1697" alt="Screenshot 2022-11-07 at 02 13 17" src="https://user-images.githubusercontent.com/15676404/200200572-be7a0a72-8601-44a0-953e-22bf22649ea9.png">

Цвет placeholder-ов в инпутах не по дизайну (текст тоже). Тексты в других тоже не как на макете. Dropdown изначально должен быть скрыт.

При фокусе почему то инпут красится в красный. Сбросить фильтры в одну строку должна быть.

Dropdown со статусами должен быть рабочим. Там не нужен placeholder. Выбранные статусы перечисляются через запятую. Если выбрано все или не выбрано ничего то будет отображаться текст "Любой"

2022-11-06 23:16 UTC, Muslik commented
common и shared это одно и тоже. shared переименуйте в modules или features

2022-11-06 23:33 UTC, Muslik requested changes
Пока что так

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Dropdown/Dropdown.jsx
> +export const Dropdown = () => (
Dropdown не переиспользуемый. Я могу в него захотеть положить инпут как при выборе страницы или кнопки как при выборе темы. Сверху комменты убрать

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Checkboxes/Checkboxes.jsx
> +export const Checkbox = ({ icon }) => (
Разделить компоненты по папкам. Файл назвать Checkbox.jsx

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Checkboxes/Checkboxes.jsx
> +export const CheckboxRadio = () => (
Просто Radio

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Button/Button.jsx
> +export const ButtonWidth = {
Вы не можете зашивать все ширину в компонент button.

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Button/buttons.module.css
> +  border-radius: 0.25rem;
Переименовать в Button.module.css

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Button/Button.jsx
> +export const ButtonHeight = {
ButtonSize. Не нужно внешним компонентам знать что тут именно ширина затрагивается

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Button/buttons.module.css
> +.long svg, .medium svg, .short svg {
svg задать класс

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Button/buttons.module.css
> +  border-radius: 0.25rem;
border-radius у всех кнопок. Задайте это один раз

2022-11-06 23:33 UTC, Muslik commented on src/components/shared/Filter/Filter.jsx
> +  const dateFromIcon = (e) => setDateFrom(e.target.value);
Причем тут Icon ?

2022-11-06 23:33 UTC, Muslik commented on src/components/shared/Filter/Filter.jsx
> +              ></Input>
Одиночные теги должны быть одиночными.

2022-11-06 23:33 UTC, Muslik commented on src/components/shared/Filter/Filter.jsx
> +                type={"number"}
Из за типа number я не могу ввести 12.12.2022

2022-11-06 23:33 UTC, Muslik commented on src/components/shared/Filter/Filter.jsx
> +                icon={
А почему вы в icon передаете кнопку

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Label/Label.jsx
> +    {control}
одно дело когда вы передаете сюда только control и title. А вы передаете кучу детей. Поэтому передавайте тот же input обычным children-ом. И postfix точно также

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Label/Label.jsx
> +  text,
Не используется

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Searchbar/Searchbar.jsx
> +import styles from "./searchbar.module.css";
Searchbar.module.css - с большой буквы

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Searchbar/Searchbar.jsx
> +  const SearchbarClosingButton = (
Это не ClosingButton, а ResetButton. Вы можете иконку сброса положить сразу в Input. И добавить props onReset

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Searchbar/Searchbar.jsx
> +  const iconVisibilityHandler = (e) => setData(e.target.value);
Причем тут iconVisibility если это поиск

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Searchbar/Searchbar.jsx
> +  const [data, setData] = useState("");
Переменная data - худжее название которое можно дать. Она не несет никакой ценности. И никак не сообщает о том что лежит в ней.

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Searchbar/Searchbar.jsx
> +        onChange={iconVisibilityHandler}
handler-ы называем:
handleChange,
handleClick,
handleDateChange,
handleDateClick

и тому подобное

2022-11-06 23:33 UTC, Muslik commented on src/components/shared/Filter/Filter.jsx
> +  const [dateTo, setdateTo] = useState("");
setDateTo - camelCase. Ниже тоже самое

2022-11-06 23:33 UTC, Muslik commented on src/components/shared/Filter/Filter.jsx
> +                onClick={() =>
Вот такие штуки выносите уже отдельно в handler-ы выше.

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Input/Input.jsx
> +    [styles.blue]: color === InputColor.blue,
Не вижу стиля для disabled.
Не вижу иконки замочка для disabled

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Input/Input.jsx
> +  const [sum, setSum] = useState("");
Этого тут быть не должно

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Input/Input.jsx
> +        onChange={onChange}
Не вижу тут value

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Header/HeaderButonChanger.jsx
> +  const HeaderButtonChangerIcon = <Icon name="sun"></Icon>;
Это выносим из общих компонентов.

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Header/HeaderButonChanger.jsx
> +      <Button prefix={HeaderButtonChangerIcon}>Свелая тема</Button>
Опечаточка

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Header/heading.module.css
> +.headingWrapper {
Файлы в одном стиле называйте.

Component.module.css

Откуда взялся heading непонятно.

2022-11-06 23:33 UTC, Muslik commented on src/components/shared/Filter/Filter.jsx
> +export const Filter = ({ children, type = "button" }) => {
Для чего тут эти пропсы

2022-11-06 23:33 UTC, Muslik commented on src/components/shared/Filter/Filter.jsx
> +  const [visibleExtendedStatusDropdown, setVisibleExtendedStatusDropdown] =
Зачем тут слово extended

isStatusesDropdownVisible

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Searchbar/Searchbar.jsx
> +  const [data, setData] = useState("");
Помимо этого Searchbar не может хранить в себе state

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Searchbar/Searchbar.jsx
> +  const [data, setData] = useState("");
Почему вы в Searchbar вкладываете что то. children тут не нужен

2022-11-06 23:33 UTC, Muslik commented on src/components/common/Searchbar/Searchbar.jsx
> +  const [data, setData] = useState("");
className никак не используется

2022-11-06 23:35 UTC, Muslik commented
<img width="593" alt="Screenshot 2022-11-07 at 02 13 04" src="https://user-images.githubusercontent.com/15676404/200201600-14f1661a-fa58-4b0a-9658-5a02f2fcad35.png">
Не должно быть ошибок в консоли

2022-11-06 23:35 UTC, Muslik commented
<img width="273" alt="Screenshot 2022-11-07 at 02 35 45" src="https://user-images.githubusercontent.com/15676404/200201639-0485c6a3-1269-4a47-84ea-99f9ba339732.png">
А крестика то и нет

2022-11-06 23:37 UTC, Muslik commented
Кнопка "Фильтры" становится синей только при открытии фильтров

2022-11-07 09:12 UTC, Muslik commented on src/components/common/Button/buttons.module.css
> +
Убрать пустые строки

2022-11-07 09:12 UTC, Muslik commented on src/components/common/Button/buttons.module.css
> +.long:hover svg, .medium:hover svg, .short:hover svg {
убрать комменты

2022-11-07 09:12 UTC, Muslik commented on src/components/common/Button/buttons.module.css
> +  color: #fff !important;
убрать important

2022-11-07 13:41 UTC, Starrkkiller commented on src/components/common/Checkboxes/Checkboxes.jsx
> +export const Checkbox = ({ icon }) => (
+

2022-11-07 13:41 UTC, Starrkkiller commented on src/components/common/Checkboxes/Checkboxes.jsx
> +export const CheckboxRadio = () => (
+

2022-11-07 13:41 UTC, Starrkkiller commented on src/components/common/Header/HeaderButonChanger.jsx
> +  const HeaderButtonChangerIcon = <Icon name="sun"></Icon>;
+

2022-11-07 13:42 UTC, Starrkkiller commented on src/components/common/Header/HeaderButonChanger.jsx
> +      <Button prefix={HeaderButtonChangerIcon}>Свелая тема</Button>
+

2022-11-07 13:42 UTC, Starrkkiller commented on src/components/common/Header/heading.module.css
> +.headingWrapper {
+

2022-11-07 13:43 UTC, Starrkkiller commented on src/components/shared/Filter/Filter.jsx
> +                type={"number"}
+

2022-11-07 13:47 UTC, Starrkkiller commented on src/components/common/Searchbar/Searchbar.jsx
> +  const SearchbarClosingButton = (
+

2022-11-07 13:48 UTC, Starrkkiller commented on src/components/shared/Filter/Filter.jsx
> +  const [dateTo, setdateTo] = useState("");
+

2022-11-07 19:02 UTC, Starrkkiller commented on src/components/common/Button/buttons.module.css
> +  border-radius: 0.25rem;
+

2022-11-07 19:03 UTC, Starrkkiller commented on src/components/common/Header/HeaderButonChanger.jsx
> +  const HeaderButtonChangerIcon = <Icon name="sun"></Icon>;
+

2022-11-07 19:03 UTC, Starrkkiller commented on src/components/common/Header/HeaderButonChanger.jsx
> +      <Button prefix={HeaderButtonChangerIcon}>Свелая тема</Button>
+

2022-11-07 19:03 UTC, Starrkkiller commented on src/components/common/Header/heading.module.css
> +.headingWrapper {
+

2022-11-07 19:03 UTC, Starrkkiller commented on src/components/common/Button/buttons.module.css
> +
+

2022-11-07 19:03 UTC, Starrkkiller commented on src/components/common/Button/buttons.module.css
> +.long:hover svg, .medium:hover svg, .short:hover svg {
+

2022-12-03 11:48 UTC, merged